const defaultRoutes = [
  {
    id: 1,
    origen: 'Terminal Central',
    destino: 'San Sebastian',
    precio: 25000,
    duracion: '2h 30m',
    servicio: 'Directo',
    serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño'],
    anden: 'Andén 5',
    estado: 'Cargando',
    progresoCarga: 75,
    horaSalida: '14:30',
    asientosDisponibles: 12,
    empresa: 'Transportes Norte',
    tipoBus: 'Bus Ejecutivo'
  },
  {
    id: 2,
    origen: 'Terminal Central',
    destino: 'San Felipe',
    precio: 35000,
    duracion: '3h 15m',
    servicio: 'Parada Corta',
    serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Snack'],
    anden: 'Andén 3',
    estado: 'Cargando',
    progresoCarga: 45,
    horaSalida: '15:15',
    asientosDisponibles: 8,
    empresa: 'Expreso Sur',
    tipoBus: 'Bus Premium'
  },
  {
    id: 3,
    origen: 'Terminal Central',
    destino: 'Cagua',
    precio: 42000,
    duracion: '4h 00m',
    servicio: 'Directo',
    serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Entretenimiento'],
    anden: 'Andén 7',
    estado: 'Cargando',
    progresoCarga: 90,
    horaSalida: '16:00',
    asientosDisponibles: 3,
    empresa: 'Línea Dorada',
    tipoBus: 'Bus Suite'
  },
  {
    id: 4,
    origen: 'Terminal Central',
    destino: 'La Victoria',
    precio: 28000,
    duracion: '2h 00m',
    servicio: 'Parada Corta',
    serviciosAdicionales: ['Aire Acondicionado', 'Baño'],
    anden: 'Andén 2',
    estado: 'Cargando',
    progresoCarga: 30,
    horaSalida: '14:45',
    asientosDisponibles: 15,
    empresa: 'Transportes Este',
    tipoBus: 'Bus Estándar'
  },
  {
    id: 5,
    origen: 'Terminal Central',
    destino: 'Ciudad F',
    precio: 38000,
    duracion: '3h 30m',
    servicio: 'Directo',
    serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Carga USB'],
    anden: 'Andén 8',
    estado: 'Cargando',
    progresoCarga: 60,
    horaSalida: '17:30',
    asientosDisponibles: 5,
    empresa: 'Expreso Oeste',
    tipoBus: 'Bus Ejecutivo'
  },
  {
    id: 6,
    origen: 'Terminal Central',
    destino: 'Ciudad G',
    precio: 32000,
    duracion: '2h 45m',
    servicio: 'Parada Corta',
    serviciosAdicionales: ['Aire Acondicionado', 'WiFi'],
    anden: 'Andén 4',
    estado: 'Cargando',
    progresoCarga: 20,
    horaSalida: '18:00',
    asientosDisponibles: 20,
    empresa: 'Transportes Norte',
    tipoBus: 'Bus Estándar'
  }
];

export default defaultRoutes;