const defaultRoutes = [{
        id: 1,
        origen: 'Terminal San Juan',
        destino: 'Maracay (Terminal)',
        precio: 4.00, // Precio promedio en $
        duracion: '1h 45m',
        servicio: 'Semi-Directo',
        serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño'],
        anden: 'Andén 5',
        estado: 'Cargando',
        progresoCarga: 75,
        horaSalida: '14:30',
        asientosDisponibles: 12,
        empresa: 'Expresos Guárico',
        tipoBus: 'Bus Ejecutivo'
    },
    {
        id: 2,
        origen: 'Terminal San Juan',
        destino: 'Valencia (Terminal)',
        precio: 7.00,
        duracion: '2h 45m',
        servicio: 'Parada Larga',
        serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Snack'],
        anden: 'Andén 3',
        estado: 'Cargando',
        progresoCarga: 45,
        horaSalida: '15:15',
        asientosDisponibles: 8,
        empresa: 'Expreso Los Llanos',
        tipoBus: 'Bus Premium'
    },
    {
        id: 3,
        origen: 'Terminal San Juan',
        destino: 'Caracas (La Bandera)',
        precio: 10.00,
        duracion: '4h 15m',
        servicio: 'Directo',
        serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Entretenimiento'],
        anden: 'Andén 7',
        estado: 'Cargando',
        progresoCarga: 90,
        horaSalida: '16:00',
        asientosDisponibles: 3,
        empresa: 'Línea Guariqueña',
        tipoBus: 'Bus Suite'
    },
    {
        id: 4,
        origen: 'Terminal San Juan',
        destino: 'Villa de Cura',
        precio: 1.00, // Esta es una ruta corta
        duracion: '35m',
        servicio: 'Parada Corta',
        serviciosAdicionales: ['Aire Acondicionado', 'Baño'],
        anden: 'Andén 2',
        estado: 'Cargando',
        progresoCarga: 30,
        horaSalida: '14:45',
        asientosDisponibles: 15,
        empresa: 'Transportes Aragua',
        tipoBus: 'Bus Estándar'
    },
    {
        id: 5,
        origen: 'Terminal San Juan',
        destino: 'Calabozo',
        precio: 6.00,
        duracion: '2h 30m',
        servicio: 'Semi-Directo',
        serviciosAdicionales: ['Aire Acondicionado', 'WiFi', 'Baño', 'Carga USB'],
        anden: 'Andén 8',
        estado: 'Cargando',
        progresoCarga: 60,
        horaSalida: '17:30',
        asientosDisponibles: 5,
        empresa: 'Expreso Oriente',
        tipoBus: 'Bus Ejecutivo'
    },
    {
        id: 6,
        origen: 'Terminal San Juan',
        destino: 'San Fernando de Apure',
        precio: 12.00,
        duracion: '5h 00m',
        servicio: 'Parada Larga',
        serviciosAdicionales: ['Aire Acondicionado', 'WiFi'],
        anden: 'Andén 4',
        estado: 'Cargando',
        progresoCarga: 20,
        horaSalida: '18:00',
        asientosDisponibles: 20,
        empresa: 'Expresos Los Llanos',
        tipoBus: 'Bus Estándar'
    }
];

export default defaultRoutes;